package maven.pojo;

public class Apply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.userId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.infoId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.permission
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.id
     *
     * @return the value of apply.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.id
     *
     * @param id the value for apply.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.userId
     *
     * @return the value of apply.userId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.userId
     *
     * @param userid the value for apply.userId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.infoId
     *
     * @return the value of apply.infoId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.infoId
     *
     * @param infoid the value for apply.infoId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setInfoid(Integer infoid) {
        this.infoid = infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.permission
     *
     * @return the value of apply.permission
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.permission
     *
     * @param permission the value for apply.permission
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }
}