package maven.pojo;

public class Grade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gradeName
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private String gradename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.id
     *
     * @return the value of grade.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.id
     *
     * @param id the value for grade.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gradeName
     *
     * @return the value of grade.gradeName
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public String getGradename() {
        return gradename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gradeName
     *
     * @param gradename the value for grade.gradeName
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setGradename(String gradename) {
        this.gradename = gradename == null ? null : gradename.trim();
    }
}