package maven.pojo;

import java.util.Date;

public class Info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.userId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.gradeId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer gradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.courseId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.period
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private String period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.date
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.money
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.permission
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.remark
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.id
     *
     * @return the value of info.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.id
     *
     * @param id the value for info.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.userId
     *
     * @return the value of info.userId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.userId
     *
     * @param userid the value for info.userId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.gradeId
     *
     * @return the value of info.gradeId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.gradeId
     *
     * @param gradeid the value for info.gradeId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.courseId
     *
     * @return the value of info.courseId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.courseId
     *
     * @param courseid the value for info.courseId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.period
     *
     * @return the value of info.period
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.period
     *
     * @param period the value for info.period
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.date
     *
     * @return the value of info.date
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.date
     *
     * @param date the value for info.date
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.money
     *
     * @return the value of info.money
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.money
     *
     * @param money the value for info.money
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.permission
     *
     * @return the value of info.permission
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.permission
     *
     * @param permission the value for info.permission
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.remark
     *
     * @return the value of info.remark
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.remark
     *
     * @param remark the value for info.remark
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}