package maven.pojo;

import java.util.Date;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.parentId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.teacherId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.parentId
     *
     * @return the value of record.parentId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.parentId
     *
     * @param parentid the value for record.parentId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.teacherId
     *
     * @return the value of record.teacherId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.teacherId
     *
     * @param teacherid the value for record.teacherId
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time
     *
     * @return the value of record.time
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time
     *
     * @param time the value for record.time
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}