package maven.pojo;

public class Usertype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertype.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertype.type
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertype.id
     *
     * @return the value of usertype.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertype.id
     *
     * @param id the value for usertype.id
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertype.type
     *
     * @return the value of usertype.type
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertype.type
     *
     * @param type the value for usertype.type
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}