package maven.dao;

import java.util.List;
import maven.pojo.Info;
import maven.pojo.Teacherinfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface InfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    int insert(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    Info selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    List<Info> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    int updateByPrimaryKey(Info record);


    List<Teacherinfo> selectTeacher();

    Info selectByUserId(int id);

    List<Info> selectPermission();

    int failInfo(int id);

    int passInfo(int id);
}