package maven.dao;

import java.util.List;
import maven.pojo.Usertype;

public interface UsertypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertype
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertype
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    int insert(Usertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertype
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    Usertype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertype
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    List<Usertype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertype
     *
     * @mbggenerated Mon Sep 02 14:34:23 CST 2019
     */
    int updateByPrimaryKey(Usertype record);
}